[default]
allow-incoming = false
allow-outgoing = true

# SSH
[[incoming.rule]]
match = { tcp-port = 22 }
allow = true

# HTTP
[[incoming.rule]]
match = { tcp-port = 80 }
allow = true

# Block connections to my arch-nemesis
[[outgoing.rule]]
match = { ip = "123.123.123.123" }
allow = false

[[outgoing.rule]]
match = { ipv6 = "1234:1234:1234:1234:1234:1234:1234:1234" }
allow = false
