[default]
allow-incoming = false
allow-outgoing = true

[[incoming.rule]]
match = { tcp-port = 1234 }
allow = true

[[incoming.rule]]
match = { ipv4 = "192.168.0.50", tcp-port = 1234 }
allow = false

[[outgoing.rule]]
match = { tcp-port = 80 }
allow = false
